# Generated by Django 6.1 on 2026-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='authors',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='thumbnail',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
